server:
    port: 8080

management:
    endpoint:
        health:
            enabled: true

convention:
    feature:
        enabled: true

hostname: "http://localhost:8082"

---
spring:
    config:
        activate:
            on-profile: pod

hostname: "http://172.20.220.20"



