apiVersion: v1
kind: Service
metadata:
  name: core-application-service
  namespace: gbp-tenant-namespace
spec:
  selector:
    app: core-application
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
